site_name: 玉子爱做题

repo_url: https://github.com/huaxv-code/huaxv-problemset
repo_name: 花续情愫缘 / huaxv-note

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true 
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.superfences

theme:
  logo: 'img/头像.png'
  favicon: 'img/头像.png'
  icon:  
    repo: fontawesome/brands/git
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  name: material
  features:
    - navigation.instant
    # - navigation.indexes
    # - navigation.tracking
    - navigation.tabs 
    # - navigation.tabs.sticky
    # - navigation.sections
    - toc.integrate # 屏蔽右侧导航栏，合并到左边
    # - navigation.expand
    # - navigation.prune
    # - navigation.prune 
    # - toc.follow
    - navigation.top
    # - toc.integrate
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: white

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      # accent: deep orange
    # - accent: green

  font:
    code: Roboto Mono
  language: zh

plugins:
  - glightbox
  # - search:
  #     # lang:
  #     #   - en
  #     #   - ja
  #     # separator: '[\s\-\.]+'
  #     separator: '[\s\u200b\-]'
  # #   separator: '[\s\u200b\-]'
  # # - with-pdf
  #   # verbose: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:

  - 简介:

    - index.md
  
  - 准备:

    - problem/准备/代码片段.md
    - problem/准备/配置sublime.md
    - problem/准备/批处理运行命令.md
  
  - 语言:
    - Java:
      - 输入: problem/语言/Java/输入.md
      - 输出: problem/语言/Java/输出.md
      - BigInteger: problem/语言/Java/BigInteger.md
      - BigDecimal: problem/语言/Java/BigDecimal.md
      - 排序: problem/语言/Java/排序.md
      - String: problem/语言/Java/String.md
      - Integer: problem/语言/Java/Integer.md
      - Double: problem/语言/Java/Double.md
      - List: problem/语言/Java/List.md
      - Queue: problem/语言/Java/Queue.md
      - Deque: problem/语言/Java/Deque.md
      - 栈: problem/语言/Java/栈.md
      - 优先队列: problem/语言/Java/优先队列.md
      - Set: problem/语言/Java/Set.md
      - Map: problem/语言/Java/Map.md
      - 模拟队列: problem/语言/Java/模拟队列.md
      - Java 数据结构: problem/语言/Java/Java 数据结构.md

    - Java 小界面:
      - 显示小窗口: problem/语言/Java 小界面/显示小窗口.md
      - 登录窗体: problem/语言/Java 小界面/登录窗体.md

    - MySQL:
      - 入门命令: problem/语言/MySQL/入门命令.md



  - 规律模拟:

    - AB提前确定输赢: problem/规律模拟/AB提前确定输赢.md
    - 小卡与质数2 : problem/规律模拟/小卡与质数2.md
    - 剩下的数 : problem/规律模拟/剩下的数.md
    - 同余特殊除法 : problem/规律模拟/同余特殊除法.md


  - 贪心:

    - H指数: problem/贪心/H指数.md
    - 最少坏区间: problem/贪心/最少坏区间.md
    - 后缀表达式最大值: problem/贪心/后缀表达式最大值.md
    - 下载插件: problem/贪心/下载插件.md


  - 分治法:

    - 逆序对: problem/分治法/逆序对.md


  - 双指针:

    - 两数之和: problem/双指针/两数之和.md
    - 单词背诵: problem/双指针/单词背诵.md
    - 逛画展: problem/双指针/逛画展.md
    - 三数之和: problem/双指针/三数之和.md
    - 移除元素: problem/双指针/移除元素.md
    - 升序数组去重: problem/双指针/升序数组去重.md
    - 最长连续不重复子序列: problem/双指针/最长连续不重复子序列.md
    - 数组元素目标值: problem/双指针/数组元素目标值.md
    - 砖块: problem/双指针/砖块.md
  - 区间信息处理:

    - 二分法:

      - 两数之和: problem/区间信息处理/二分法/两数之和.md
      - 跳石头: problem/区间信息处理/二分法/跳石头.md
      - 路标设置: problem/区间信息处理/二分法/路标设置.md
      - 序列划分: problem/区间信息处理/二分法/序列划分.md
      - 通往奥格瑞玛的道路: problem/区间信息处理/二分法/通往奥格瑞玛的道路.md
      - H指数: problem/区间信息处理/二分法/H指数.md
      - 进击的奶牛 : problem/区间信息处理/二分法/进击的奶牛.md
      - 过生日（实数二分）: problem/区间信息处理/二分法/过生日.md
      - 砍原木 : problem/区间信息处理/二分法/砍原木.md
      - 寻找段落 : problem/区间信息处理/二分法/寻找段落.md
      - 称重: problem/区间信息处理/二分法/称重.md
      - 小卡与质数2 : problem/区间信息处理/二分法/小卡与质数2.md
      - 我在哪: problem/区间信息处理/二分法/我在哪.md

    - 三分法:

      - 【模板】三分法 : problem/区间信息处理/三分法/实数三分法.md
      - 二次方程极小值 : problem/区间信息处理/三分法/二次方程极小值.md
      - 称重: problem/区间信息处理/三分法/称重.md
      - 期末考试: problem/区间信息处理/三分法/期末考试.md

    - 队列:
      - 中位数: problem/区间信息处理/队列/中位数.md

    - 前缀差分:

      - 区间重叠问题: problem/区间信息处理/前缀差分/区间重叠问题.md
      - 出行计划: problem/区间信息处理/前缀差分/出行计划.md
      - 最大子段和: problem/区间信息处理/前缀差分/最大子段和.md
      - 求和: problem/区间信息处理/前缀差分/求和.md
      - 区域重叠问题: problem/区间信息处理/前缀差分/区域重叠问题.md
      - 海底高铁: problem/区间信息处理/前缀差分/海底高铁.md
      - 最大加权矩形: problem/区间信息处理/前缀差分/最大加权矩形.md
      - 推导二维前缀和数组: problem/区间信息处理/前缀差分/推导二维前缀和数组.md
      - 光骓者的荣耀: problem/区间信息处理/前缀差分/光骓者的荣耀.md
      - K 倍区间个数: problem/区间信息处理/前缀差分/K倍区间个数.md
      - 截断数组: problem/区间信息处理/前缀差分/截断数组.md

    - 滑动窗口:

      - 滑动窗口 : problem/区间信息处理/滑动窗口/滑动窗口.md
      - m区间内的最小值 : problem/区间信息处理/滑动窗口/m区间内的最小值.md
      - 寻找段落 : problem/区间信息处理/滑动窗口/寻找段落.md

    - 并查集:

      - 全球变暖 : problem/区间信息处理/并查集/全球变暖.md

    - 线段树:
      - 区间和: problem/区间信息处理/线段树/区间和.md
      - 区间修改与查询: problem/区间信息处理/线段树/区间修改与查询.md
      - 又乘又加的区间处理: problem/区间信息处理/线段树/又乘又加的区间处理.md
      - 逆序对: problem/区间信息处理/线段树/逆序对.md
      - 第 k 位数: problem/区间信息处理/线段树/第 k 位数.md
      - XOR的艺术: problem/区间信息处理/线段树/XOR的艺术.md
      - 火柴排队: problem/区间信息处理/线段树/火柴排队.md
      - 滑动窗口: problem/区间信息处理/线段树/滑动窗口.md
      - 根据身高重建队列: problem/区间信息处理/线段树/根据身高重建队列.md
      - 最长递增子序列: problem/区间信息处理/线段树/最长递增子序列.md
      - 导弹拦截: problem/区间信息处理/线段树/导弹拦截.md
      - 最长递增子序列的个数: problem/区间信息处理/线段树/最长递增子序列的个数.md
      - 统计作战单位数: problem/区间信息处理/线段树/统计作战单位数.md
      - 我的日程安排表 I: problem/区间信息处理/线段树/我的日程安排表 I.md
      - 查询带键的排列: problem/区间信息处理/线段树/查询带键的排列.md
      - 最长上传前缀: problem/区间信息处理/线段树/最长上传前缀.md
      - 数字流的秩: problem/区间信息处理/线段树/数字流的秩.md
  

  - 倍增法:

    - 快速幂: problem/倍增法/快速幂.md
    - 国旗计划: problem/倍增法/国旗计划.md
    - 跑路: problem/倍增法/跑路.md
    - 区间最小值: problem/倍增法/区间最小值.md


  - 数学:

    - 数学:

      - 猜中的期望次数: problem/数学/数学/猜中的期望次数.md
      - 重叠面积比值: problem/数学/数学/重叠面积比值.md
      - 同余特殊除法 : problem/数学/数学/同余特殊除法.md
      - 分扑克牌 : problem/数学/数学/分扑克牌.md
    
    - 素数:

      - 素性探测: problem/数学/素数/素性探测.md
      - 线性筛素数表: problem/数学/素数/线性筛素数表.md


  - 搜索:

    - 迷宫之谜 : problem/搜索/迷宫之谜.md
    - 全球变暖 : problem/搜索/全球变暖.md
    - 跳蚱蜢: problem/搜索/跳蚱蜢.md
    - 农夫找奶牛: problem/搜索/农夫找奶牛.md


  - 动态规划:

    - 递推:
      - 台阶问题（简单版）: problem/动态规划/递推/台阶问题1.md
      - 台阶问题（困难版）: problem/动态规划/递推/台阶问题2.md
      - 很多个 1 取模 : problem/动态规划/递推/很多个1取模.md
      - 斐波那契数 : problem/动态规划/递推/斐波那契数.md

    - 01 背包问题:
      - 01 背包: problem/动态规划/01 背包问题/01背包.md
      - 01 背包变换解法: problem/动态规划/01 背包问题/01 背包变换解法.md
      - 01 背包变式: problem/动态规划/01 背包问题/01 背包变式.md
      - 装箱问题 : problem/动态规划/01 背包问题/装箱问题.md
      - 开心的金明 : problem/动态规划/01 背包问题/开学的金明.md
      - 精卫填海: problem/动态规划/01 背包问题/精卫填海.md

    - 分组背包问题:
      - 分组背包: problem/动态规划/分组背包问题/分组背包.md

    - 多重背包问题:
      - 多重背包: problem/动态规划/多重背包问题/多重背包.md

    - 完全背包问题:
      - 完全背包: problem/动态规划/完全背包问题/完全背包.md
      - 最少四次方数之和: problem/动态规划/完全背包问题/最少四次方数之和.md

    - 二维费用背包:
      - 二维费用背包: problem/动态规划/二维费用背包/二维费用背包.md

    - 书本整理问题:
      - 书本整理: problem/动态规划/书本整理问题/书本整理.md

    - 最长公共子序列:
      - 最长公共子序列: problem/动态规划/最长公共子序列/最长公共子序列.md

    - 最长递增子序列:
      - 最长递增子序列: problem/动态规划/最长递增子序列/最长递增子序列.md

    - 编辑距离:
      - 编辑距离: problem/动态规划/编辑距离/编辑距离.md

    - 正则表达式匹配:
      - 正则表达式匹配: problem/动态规划/正则表达式匹配/正则表达式匹配.md
    
    - 最长回文子串:
      - 最长回文子串: problem/动态规划/最长回文子串/最长回文子串.md

    - 线性 dp:
      - 最长的有效括号: problem/动态规划/线性 dp/最长的有效括号.md
      - 爬楼梯的最少花费: problem/动态规划/线性 dp/爬楼梯的最少花费.md
      - 除数博弈: problem/动态规划/线性 dp/除数博弈.md
      - 传递信息: problem/动态规划/线性 dp/传递信息.md
      - 连续子数组最大和: problem/动态规划/线性 dp/连续子数组最大和.md
      - 二进制中 1 的个数: problem/动态规划/线性 dp/二进制中 1 的个数.md
      - 吞并数字: problem/动态规划/线性 dp/吞并数字.md
      - 跳跃游戏 1: problem/动态规划/线性 dp/跳跃游戏.md
      - 跳跃游戏 2: problem/动态规划/线性 dp/跳跃游戏 2.md
      - 不同路径 1: problem/动态规划/线性 dp/不同路径.md
      - 不同路径 2: problem/动态规划/线性 dp/不同路径 2.md
      - 最小路径和: problem/动态规划/线性 dp/最小路径和.md
      - 解码方法: problem/动态规划/线性 dp/解码方法.md
      - 不同的二叉搜索树 1: problem/动态规划/线性 dp/不同的二叉搜索树 1.md
      - 不同的二叉搜索树 2: problem/动态规划/线性 dp/不同的二叉搜索树 2.md
      - 黑白棋: problem/动态规划/线性 dp/黑白棋.md
      - 调配化学药剂: problem/动态规划/线性 dp/调配化学药剂.md
      - 交错字符串: problem/动态规划/线性 dp/交错字符串.md
      - 三角形最小路径和: problem/动态规划/线性 dp/三角形最小路径和.md
      - 买卖股票的最佳时机 2: problem/动态规划/线性 dp/买卖股票的最佳时机2.md
      - 分割回文串: problem/动态规划/线性 dp/分割回文串.md
      - 单词拆分: problem/动态规划/线性 dp/单词拆分.md
      - 乘积最大子数组: problem/动态规划/线性 dp/乘积最大子数组.md
      - 打家劫舍 2: problem/动态规划/线性 dp/打家劫舍 2.md
  - 字符串:
    - KMP:
      - KMP: problem/字符串/KMP/KMP.md
